workflows:
  android:
    name: Android Build Fix

    scripts:
      - chmod +x gradlew || true
      - ./gradlew clean || true
      - ./gradlew assembleDebug --stacktrace || gradle assembleDebug --stacktrace

    artifacts:
      - "**/*.apk"
