workflows:
  android:
    name: Android Build

    scripts:
      - chmod +x gradlew || true
      - ./gradlew assembleDebug || gradle assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
